name: Build and Push Images
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log into Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push webapp
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/webapp:latest
      - name: Build and push db
        uses: docker/build-push-action@v4
        with:
          context: ./db
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/db:latest